//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlakaSehir {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlakaSehir.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belediye Başkanı hangi partiden?.
        /// </summary>
        internal static string SoruBelediyeBaskani {
            get {
                return ResourceManager.GetString("SoruBelediyeBaskani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe belediyeleri hangi partilerden?.
        /// </summary>
        internal static string SoruIlceBelediyeler {
            get {
                return ResourceManager.GetString("SoruIlceBelediyeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaç ilçesi var?.
        /// </summary>
        internal static string SoruIlceSayisi {
            get {
                return ResourceManager.GetString("SoruIlceSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölçülmüş en yüksek sıcaklık?.
        /// </summary>
        internal static string SoruMaxTemp {
            get {
                return ResourceManager.GetString("SoruMaxTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölçülmüş en düşük sıcaklık?.
        /// </summary>
        internal static string SoruMinTemp {
            get {
                return ResourceManager.GetString("SoruMinTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nüfusu kaç?.
        /// </summary>
        internal static string SoruNufus {
            get {
                return ResourceManager.GetString("SoruNufus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km² başına düşen insan sayısı?.
        /// </summary>
        internal static string SoruNufusPerKmSq {
            get {
                return ResourceManager.GetString("SoruNufusPerKmSq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon alan kodu kaç?.
        /// </summary>
        internal static string SoruTelefonKod {
            get {
                return ResourceManager.GetString("SoruTelefonKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaç adet üniversite var?.
        /// </summary>
        internal static string SoruUniSayisi {
            get {
                return ResourceManager.GetString("SoruUniSayisi", resourceCulture);
            }
        }
    }
}
