#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PlakaSehir.Droid.Resource", IsApplication=true)]

namespace PlakaSehir.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int adana640 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int adiyaman640 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int afyonkarahisar640 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int agri640 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int aksaray640 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int amasya640 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ankara640 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int antalya640 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ardahan640 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int artvin640 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int aydin640 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int balikesir640 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bartin640 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int batman640 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bayburt640 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bilecik640 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bingol640 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bitlis640 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bolu640 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int burdur640 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bursa640 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int canakkale640 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int cankiri640 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int corum640 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int denizli640 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int diyarbakir640 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int duzce640 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int edirne640 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int elazig640 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int erzincan640 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int erzurum640 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int eskisehir640 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int gaziantep640 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int giresun640 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int gumushane640 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int hakkari640 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int hatay640 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int icon = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int igdir640 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int isparta640 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int istanbul640 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int izmir640 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int kahramanmaras640 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int karabuk640 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int karaman640 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int kars640 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int kastamonu640 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int kayseri640 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int kilis640 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int kirikkale640 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int kirklareli640 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int kirsehir640 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int kocaeli640 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int konya640 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int kutahya640 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int malatya640 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int manisa640 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int mardin640 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int mersin640 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int mugla640 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int mus640 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int nevsehir640 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int nigde640 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ordu640 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int osmaniye640 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int rize640 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int sakarya640 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int samsun640 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int sanliurfa640 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int siirt640 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int sinop640 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int sirnak640 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int sivas640 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int tekirdag640 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int tokat640 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int trabzon640 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int tunceli640 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int usak640 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int van640 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int yalova640 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int yozgat640 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int zonguldak640 = 2130837585;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
